-- ─────────────────────────────────────────────
-- Neovim Colorscheme — Generated by Matugen
-- Do NOT edit manually, this file is overwritten
-- ─────────────────────────────────────────────

vim.cmd("hi clear")
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local hl = vim.api.nvim_set_hl

-- ── Editor ──
hl(0, "Normal",       { fg = "{{colors.on_surface.default.hex}}", bg = "NONE" })
hl(0, "NormalFloat",   { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "FloatBorder",   { fg = "{{colors.outline.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "ColorColumn",   { bg = "{{colors.surface_container.default.hex}}" })
hl(0, "CursorLine",    { bg = "{{colors.surface_container.default.hex}}" })
hl(0, "CursorLineNr",  { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "LineNr",         { fg = "{{colors.outline.default.hex}}" })
hl(0, "SignColumn",     { fg = "{{colors.outline.default.hex}}", bg = "NONE" })
hl(0, "FoldColumn",     { fg = "{{colors.outline.default.hex}}", bg = "NONE" })
hl(0, "Folded",         { fg = "{{colors.on_surface_variant.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })

-- ── Selection & Search ──
hl(0, "Visual",      { bg = "{{colors.primary_container.default.hex}}" })
hl(0, "VisualNOS",   { bg = "{{colors.primary_container.default.hex}}" })
hl(0, "Search",      { fg = "{{colors.on_tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" })
hl(0, "IncSearch",   { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}" })
hl(0, "CurSearch",   { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "MatchParen",  { fg = "{{colors.primary.default.hex}}", bold = true, underline = true })

-- ── Statusline & Tabline ──
hl(0, "StatusLine",   { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "StatusLineNC", { fg = "{{colors.outline.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "TabLine",      { fg = "{{colors.on_surface_variant.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "TabLineSel",   { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}" })
hl(0, "TabLineFill",  { bg = "{{colors.surface_container.default.hex}}" })
hl(0, "WinSeparator", { fg = "{{colors.outline_variant.default.hex}}" })

-- ── Popup Menu ──
hl(0, "Pmenu",      { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container.default.hex}}" })
hl(0, "PmenuSel",   { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}" })
hl(0, "PmenuSbar",  { bg = "{{colors.surface_container.default.hex}}" })
hl(0, "PmenuThumb", { bg = "{{colors.outline.default.hex}}" })

-- ── Messages ──
hl(0, "ErrorMsg",   { fg = "{{colors.error.default.hex}}", bold = true })
hl(0, "WarningMsg", { fg = "{{colors.secondary.default.hex}}", bold = true })
hl(0, "ModeMsg",    { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "MoreMsg",    { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "Question",   { fg = "{{colors.tertiary.default.hex}}" })

-- ── Diff ──
hl(0, "DiffAdd",    { bg = "{{colors.tertiary_container.default.hex}}" })
hl(0, "DiffChange", { bg = "{{colors.secondary_container.default.hex}}" })
hl(0, "DiffDelete", { bg = "{{colors.error_container.default.hex}}" })
hl(0, "DiffText",   { bg = "{{colors.primary_container.default.hex}}" })

-- ── Misc ──
hl(0, "NonText",     { fg = "{{colors.outline_variant.default.hex}}" })
hl(0, "SpecialKey",  { fg = "{{colors.outline_variant.default.hex}}" })
hl(0, "Directory",   { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "Title",       { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "Conceal",     { fg = "{{colors.outline.default.hex}}" })
hl(0, "Whitespace",  { fg = "{{colors.outline_variant.default.hex}}" })

-- ══════════════════════════════════════════════
-- SYNTAX HIGHLIGHTING
-- ══════════════════════════════════════════════

hl(0, "Comment",     { fg = "{{colors.outline.default.hex}}", italic = true })

hl(0, "Constant",    { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "String",      { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "Character",   { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "Number",      { fg = "{{colors.secondary.default.hex}}" })
hl(0, "Boolean",     { fg = "{{colors.secondary.default.hex}}", bold = true })
hl(0, "Float",       { fg = "{{colors.secondary.default.hex}}" })

hl(0, "Identifier",  { fg = "{{colors.on_surface.default.hex}}" })
hl(0, "Function",    { fg = "{{colors.primary.default.hex}}", bold = true })

hl(0, "Statement",   { fg = "{{colors.primary.default.hex}}" })
hl(0, "Conditional", { fg = "{{colors.primary.default.hex}}" })
hl(0, "Repeat",      { fg = "{{colors.primary.default.hex}}" })
hl(0, "Label",       { fg = "{{colors.primary.default.hex}}" })
hl(0, "Operator",    { fg = "{{colors.on_surface_variant.default.hex}}" })
hl(0, "Keyword",     { fg = "{{colors.primary.default.hex}}", italic = true })
hl(0, "Exception",   { fg = "{{colors.error.default.hex}}" })

hl(0, "PreProc",     { fg = "{{colors.secondary.default.hex}}" })
hl(0, "Include",     { fg = "{{colors.secondary.default.hex}}" })
hl(0, "Define",      { fg = "{{colors.secondary.default.hex}}" })
hl(0, "Macro",       { fg = "{{colors.secondary.default.hex}}" })

hl(0, "Type",        { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "StorageClass",{ fg = "{{colors.primary.default.hex}}" })
hl(0, "Structure",   { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "Typedef",     { fg = "{{colors.tertiary.default.hex}}" })

hl(0, "Special",     { fg = "{{colors.secondary.default.hex}}" })
hl(0, "SpecialChar", { fg = "{{colors.secondary.default.hex}}" })
hl(0, "Tag",         { fg = "{{colors.primary.default.hex}}" })
hl(0, "Delimiter",   { fg = "{{colors.on_surface_variant.default.hex}}" })
hl(0, "SpecialComment", { fg = "{{colors.outline.default.hex}}", bold = true })
hl(0, "Debug",       { fg = "{{colors.error.default.hex}}" })

hl(0, "Underlined",  { underline = true })
hl(0, "Error",       { fg = "{{colors.on_error.default.hex}}", bg = "{{colors.error.default.hex}}" })
hl(0, "Todo",        { fg = "{{colors.on_primary_container.default.hex}}", bg = "{{colors.primary_container.default.hex}}", bold = true })

-- ══════════════════════════════════════════════
-- TREESITTER
-- ══════════════════════════════════════════════

hl(0, "@variable",           { fg = "{{colors.on_surface.default.hex}}" })
hl(0, "@variable.builtin",   { fg = "{{colors.secondary.default.hex}}", italic = true })
hl(0, "@variable.parameter", { fg = "{{colors.on_surface_variant.default.hex}}", italic = true })
hl(0, "@variable.member",    { fg = "{{colors.on_surface.default.hex}}" })

hl(0, "@constant",         { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "@constant.builtin", { fg = "{{colors.tertiary.default.hex}}", bold = true })
hl(0, "@constant.macro",   { fg = "{{colors.tertiary.default.hex}}" })

hl(0, "@string",        { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "@string.escape",  { fg = "{{colors.secondary.default.hex}}", bold = true })
hl(0, "@string.regex",   { fg = "{{colors.secondary.default.hex}}" })

hl(0, "@number",   { fg = "{{colors.secondary.default.hex}}" })
hl(0, "@boolean",  { fg = "{{colors.secondary.default.hex}}", bold = true })
hl(0, "@float",    { fg = "{{colors.secondary.default.hex}}" })

hl(0, "@function",          { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "@function.builtin",  { fg = "{{colors.primary.default.hex}}" })
hl(0, "@function.call",     { fg = "{{colors.primary.default.hex}}" })
hl(0, "@function.macro",    { fg = "{{colors.secondary.default.hex}}" })
hl(0, "@function.method",   { fg = "{{colors.primary.default.hex}}" })

hl(0, "@keyword",           { fg = "{{colors.primary.default.hex}}", italic = true })
hl(0, "@keyword.function",  { fg = "{{colors.primary.default.hex}}", italic = true })
hl(0, "@keyword.operator",  { fg = "{{colors.on_surface_variant.default.hex}}" })
hl(0, "@keyword.return",    { fg = "{{colors.primary.default.hex}}", italic = true })
hl(0, "@keyword.conditional", { fg = "{{colors.primary.default.hex}}" })
hl(0, "@keyword.repeat",    { fg = "{{colors.primary.default.hex}}" })
hl(0, "@keyword.import",    { fg = "{{colors.secondary.default.hex}}" })
hl(0, "@keyword.exception", { fg = "{{colors.error.default.hex}}" })

hl(0, "@type",          { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "@type.builtin",  { fg = "{{colors.tertiary.default.hex}}", italic = true })

hl(0, "@property",    { fg = "{{colors.on_surface.default.hex}}" })
hl(0, "@constructor",  { fg = "{{colors.tertiary.default.hex}}" })

hl(0, "@punctuation.bracket",   { fg = "{{colors.on_surface_variant.default.hex}}" })
hl(0, "@punctuation.delimiter", { fg = "{{colors.on_surface_variant.default.hex}}" })
hl(0, "@punctuation.special",   { fg = "{{colors.secondary.default.hex}}" })

hl(0, "@comment",      { fg = "{{colors.outline.default.hex}}", italic = true })
hl(0, "@comment.todo",  { fg = "{{colors.on_primary_container.default.hex}}", bg = "{{colors.primary_container.default.hex}}", bold = true })
hl(0, "@comment.note",  { fg = "{{colors.on_tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" })
hl(0, "@comment.error", { fg = "{{colors.on_error_container.default.hex}}", bg = "{{colors.error_container.default.hex}}" })

hl(0, "@tag",           { fg = "{{colors.primary.default.hex}}" })
hl(0, "@tag.attribute",  { fg = "{{colors.tertiary.default.hex}}", italic = true })
hl(0, "@tag.delimiter",  { fg = "{{colors.on_surface_variant.default.hex}}" })

hl(0, "@markup.heading",    { fg = "{{colors.primary.default.hex}}", bold = true })
hl(0, "@markup.bold",       { bold = true })
hl(0, "@markup.italic",     { italic = true })
hl(0, "@markup.link",       { fg = "{{colors.primary.default.hex}}", underline = true })
hl(0, "@markup.link.url",   { fg = "{{colors.tertiary.default.hex}}", underline = true })
hl(0, "@markup.raw",        { fg = "{{colors.secondary.default.hex}}" })
hl(0, "@markup.list",       { fg = "{{colors.primary.default.hex}}" })

-- ══════════════════════════════════════════════
-- DIAGNOSTICS
-- ══════════════════════════════════════════════

hl(0, "DiagnosticError",          { fg = "{{colors.error.default.hex}}" })
hl(0, "DiagnosticWarn",           { fg = "{{colors.secondary.default.hex}}" })
hl(0, "DiagnosticInfo",           { fg = "{{colors.tertiary.default.hex}}" })
hl(0, "DiagnosticHint",           { fg = "{{colors.outline.default.hex}}" })
hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "{{colors.error.default.hex}}" })
hl(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "{{colors.secondary.default.hex}}" })
hl(0, "DiagnosticUnderlineInfo",  { undercurl = true, sp = "{{colors.tertiary.default.hex}}" })
hl(0, "DiagnosticUnderlineHint",  { undercurl = true, sp = "{{colors.outline.default.hex}}" })
