-- ─────────────────────────────────────────────
-- Neovim Colorscheme — Generated by Matugen
-- Do NOT edit manually, this file is overwritten
-- ─────────────────────────────────────────────

vim.cmd("hi clear")
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local hl = vim.api.nvim_set_hl

-- ── Editor ──
hl(0, "Normal",       { fg = "#e2e2e9", bg = "NONE" })
hl(0, "NormalFloat",   { fg = "#e2e2e9", bg = "#1e2025" })
hl(0, "FloatBorder",   { fg = "#8e9099", bg = "#1e2025" })
hl(0, "ColorColumn",   { bg = "#1e2025" })
hl(0, "CursorLine",    { bg = "#1e2025" })
hl(0, "CursorLineNr",  { fg = "#abc7ff", bold = true })
hl(0, "LineNr",         { fg = "#8e9099" })
hl(0, "SignColumn",     { fg = "#8e9099", bg = "NONE" })
hl(0, "FoldColumn",     { fg = "#8e9099", bg = "NONE" })
hl(0, "Folded",         { fg = "#c4c6d0", bg = "#1e2025" })

-- ── Selection & Search ──
hl(0, "Visual",      { bg = "#284777" })
hl(0, "VisualNOS",   { bg = "#284777" })
hl(0, "Search",      { fg = "#fad8fd", bg = "#573e5c" })
hl(0, "IncSearch",   { fg = "#0b305f", bg = "#abc7ff" })
hl(0, "CurSearch",   { fg = "#0b305f", bg = "#abc7ff", bold = true })
hl(0, "MatchParen",  { fg = "#abc7ff", bold = true, underline = true })

-- ── Statusline & Tabline ──
hl(0, "StatusLine",   { fg = "#e2e2e9", bg = "#1e2025" })
hl(0, "StatusLineNC", { fg = "#8e9099", bg = "#1e2025" })
hl(0, "TabLine",      { fg = "#c4c6d0", bg = "#1e2025" })
hl(0, "TabLineSel",   { fg = "#0b305f", bg = "#abc7ff" })
hl(0, "TabLineFill",  { bg = "#1e2025" })
hl(0, "WinSeparator", { fg = "#44474e" })

-- ── Popup Menu ──
hl(0, "Pmenu",      { fg = "#e2e2e9", bg = "#1e2025" })
hl(0, "PmenuSel",   { fg = "#0b305f", bg = "#abc7ff" })
hl(0, "PmenuSbar",  { bg = "#1e2025" })
hl(0, "PmenuThumb", { bg = "#8e9099" })

-- ── Messages ──
hl(0, "ErrorMsg",   { fg = "#ffb4ab", bold = true })
hl(0, "WarningMsg", { fg = "#bec6dc", bold = true })
hl(0, "ModeMsg",    { fg = "#abc7ff", bold = true })
hl(0, "MoreMsg",    { fg = "#ddbce0" })
hl(0, "Question",   { fg = "#ddbce0" })

-- ── Diff ──
hl(0, "DiffAdd",    { bg = "#573e5c" })
hl(0, "DiffChange", { bg = "#3e4759" })
hl(0, "DiffDelete", { bg = "#93000a" })
hl(0, "DiffText",   { bg = "#284777" })

-- ── Misc ──
hl(0, "NonText",     { fg = "#44474e" })
hl(0, "SpecialKey",  { fg = "#44474e" })
hl(0, "Directory",   { fg = "#abc7ff", bold = true })
hl(0, "Title",       { fg = "#abc7ff", bold = true })
hl(0, "Conceal",     { fg = "#8e9099" })
hl(0, "Whitespace",  { fg = "#44474e" })

-- ══════════════════════════════════════════════
-- SYNTAX HIGHLIGHTING
-- ══════════════════════════════════════════════

hl(0, "Comment",     { fg = "#8e9099", italic = true })

hl(0, "Constant",    { fg = "#ddbce0" })
hl(0, "String",      { fg = "#ddbce0" })
hl(0, "Character",   { fg = "#ddbce0" })
hl(0, "Number",      { fg = "#bec6dc" })
hl(0, "Boolean",     { fg = "#bec6dc", bold = true })
hl(0, "Float",       { fg = "#bec6dc" })

hl(0, "Identifier",  { fg = "#e2e2e9" })
hl(0, "Function",    { fg = "#abc7ff", bold = true })

hl(0, "Statement",   { fg = "#abc7ff" })
hl(0, "Conditional", { fg = "#abc7ff" })
hl(0, "Repeat",      { fg = "#abc7ff" })
hl(0, "Label",       { fg = "#abc7ff" })
hl(0, "Operator",    { fg = "#c4c6d0" })
hl(0, "Keyword",     { fg = "#abc7ff", italic = true })
hl(0, "Exception",   { fg = "#ffb4ab" })

hl(0, "PreProc",     { fg = "#bec6dc" })
hl(0, "Include",     { fg = "#bec6dc" })
hl(0, "Define",      { fg = "#bec6dc" })
hl(0, "Macro",       { fg = "#bec6dc" })

hl(0, "Type",        { fg = "#ddbce0" })
hl(0, "StorageClass",{ fg = "#abc7ff" })
hl(0, "Structure",   { fg = "#ddbce0" })
hl(0, "Typedef",     { fg = "#ddbce0" })

hl(0, "Special",     { fg = "#bec6dc" })
hl(0, "SpecialChar", { fg = "#bec6dc" })
hl(0, "Tag",         { fg = "#abc7ff" })
hl(0, "Delimiter",   { fg = "#c4c6d0" })
hl(0, "SpecialComment", { fg = "#8e9099", bold = true })
hl(0, "Debug",       { fg = "#ffb4ab" })

hl(0, "Underlined",  { underline = true })
hl(0, "Error",       { fg = "#690005", bg = "#ffb4ab" })
hl(0, "Todo",        { fg = "#d7e3ff", bg = "#284777", bold = true })

-- ══════════════════════════════════════════════
-- TREESITTER
-- ══════════════════════════════════════════════

hl(0, "@variable",           { fg = "#e2e2e9" })
hl(0, "@variable.builtin",   { fg = "#bec6dc", italic = true })
hl(0, "@variable.parameter", { fg = "#c4c6d0", italic = true })
hl(0, "@variable.member",    { fg = "#e2e2e9" })

hl(0, "@constant",         { fg = "#ddbce0" })
hl(0, "@constant.builtin", { fg = "#ddbce0", bold = true })
hl(0, "@constant.macro",   { fg = "#ddbce0" })

hl(0, "@string",        { fg = "#ddbce0" })
hl(0, "@string.escape",  { fg = "#bec6dc", bold = true })
hl(0, "@string.regex",   { fg = "#bec6dc" })

hl(0, "@number",   { fg = "#bec6dc" })
hl(0, "@boolean",  { fg = "#bec6dc", bold = true })
hl(0, "@float",    { fg = "#bec6dc" })

hl(0, "@function",          { fg = "#abc7ff", bold = true })
hl(0, "@function.builtin",  { fg = "#abc7ff" })
hl(0, "@function.call",     { fg = "#abc7ff" })
hl(0, "@function.macro",    { fg = "#bec6dc" })
hl(0, "@function.method",   { fg = "#abc7ff" })

hl(0, "@keyword",           { fg = "#abc7ff", italic = true })
hl(0, "@keyword.function",  { fg = "#abc7ff", italic = true })
hl(0, "@keyword.operator",  { fg = "#c4c6d0" })
hl(0, "@keyword.return",    { fg = "#abc7ff", italic = true })
hl(0, "@keyword.conditional", { fg = "#abc7ff" })
hl(0, "@keyword.repeat",    { fg = "#abc7ff" })
hl(0, "@keyword.import",    { fg = "#bec6dc" })
hl(0, "@keyword.exception", { fg = "#ffb4ab" })

hl(0, "@type",          { fg = "#ddbce0" })
hl(0, "@type.builtin",  { fg = "#ddbce0", italic = true })

hl(0, "@property",    { fg = "#e2e2e9" })
hl(0, "@constructor",  { fg = "#ddbce0" })

hl(0, "@punctuation.bracket",   { fg = "#c4c6d0" })
hl(0, "@punctuation.delimiter", { fg = "#c4c6d0" })
hl(0, "@punctuation.special",   { fg = "#bec6dc" })

hl(0, "@comment",      { fg = "#8e9099", italic = true })
hl(0, "@comment.todo",  { fg = "#d7e3ff", bg = "#284777", bold = true })
hl(0, "@comment.note",  { fg = "#fad8fd", bg = "#573e5c" })
hl(0, "@comment.error", { fg = "#ffdad6", bg = "#93000a" })

hl(0, "@tag",           { fg = "#abc7ff" })
hl(0, "@tag.attribute",  { fg = "#ddbce0", italic = true })
hl(0, "@tag.delimiter",  { fg = "#c4c6d0" })

hl(0, "@markup.heading",    { fg = "#abc7ff", bold = true })
hl(0, "@markup.bold",       { bold = true })
hl(0, "@markup.italic",     { italic = true })
hl(0, "@markup.link",       { fg = "#abc7ff", underline = true })
hl(0, "@markup.link.url",   { fg = "#ddbce0", underline = true })
hl(0, "@markup.raw",        { fg = "#bec6dc" })
hl(0, "@markup.list",       { fg = "#abc7ff" })

-- ══════════════════════════════════════════════
-- DIAGNOSTICS
-- ══════════════════════════════════════════════

hl(0, "DiagnosticError",          { fg = "#ffb4ab" })
hl(0, "DiagnosticWarn",           { fg = "#bec6dc" })
hl(0, "DiagnosticInfo",           { fg = "#ddbce0" })
hl(0, "DiagnosticHint",           { fg = "#8e9099" })
hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#ffb4ab" })
hl(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#bec6dc" })
hl(0, "DiagnosticUnderlineInfo",  { undercurl = true, sp = "#ddbce0" })
hl(0, "DiagnosticUnderlineHint",  { undercurl = true, sp = "#8e9099" })
